//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPTO_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public int Id { get; set; }

        public Nullable<int> nOS { get; set; }

        public string TituloServico { get; set; }

        public string CNPJCliente { get; set; }

        public string NomeCliente { get; set; }

        public string CPFPrestadorServico { get; set; }

        public string NomePrestadorServico { get; set; }

        public Nullable<System.DateTime> DataExecucao { get; set; }

        public Nullable<decimal> ValorServico { get; set; }
    }
}
